name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Builds:
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: yarn
      - name: Compress Build Outputs
        run: |
          mkdir builds
          tar --exclude='./builds' --exclude='./.github' --exclude='./.git'  -cf builds/terminalizer.tar .
      - uses: actions/upload-artifact@v2
        with:
          name: Build Location Change
          path: builds/gdutils-${{ steps.get_version.outputs.VERSION }}.tar

      - run: |
          mv builds/terminalizer.tar terminalizer.tar
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            terminalizer.tar
